// conference-organaizer/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { EventOrganizer } from "./models/event-organizer.class";
import { Conference } from "./models/conference.class";
import { FormControl, FormGroup } from "@angular/forms";
import { Topic } from "./models/topic.class";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'conference-organaizer';
  eventOrganizer!: EventOrganizer;
  file?: File;
  fileContent?: string;
  topics: Topic[] = [];
  event: { topic: string, activities: string[] }[] = [];

  async organizarEvento() {
    if (!this.fileContent) return;

    const topicsFromFile = this.setData(this.fileContent)

    const conferences: Conference[] = topicsFromFile.map(conference => new Conference(conference.time, conference.topic))

    this.eventOrganizer = new EventOrganizer({
        conferences,
        morningStartTime: 9,
        morningEndTime: 12,
        lunchTime: 12,
        minSocialEventTime: 16,
        maxSocialEventTime: 17,
        afternoonStartTime: 13,
      }
    )

    this.topics = this.eventOrganizer.organizeConferencesInTopics()
    this.event = [];
    for (let topic of this.topics) {
      const event: { topic: string, activities: string[] } = {topic: topic.name, activities: []};

      for (let activity of topic.activities) {
        if (activity instanceof Conference) {
          event.activities.push(`${activity.startTime?.toLocaleTimeString('en-US', {
            hour: "numeric",
            minute: "numeric"
          })} ${activity.topic} ${activity.time}min`);
        } else {
          event.activities.push(`${activity.startTime?.toLocaleTimeString('en-US', {
            hour: "numeric",
            minute: "numeric"
          })} ${activity.type}`);
        }

      }
      this.event.push(event);
    }
  }

  setData(textInput: string) {

    const topics: {
      topic: string
      time: number
    }[] = [];

    textInput = textInput.replaceAll('\n', '');

    const topicsWithTime = textInput.split('min')

    topicsWithTime.forEach((topicWithTime) => {

      const timePart = topicWithTime.match(/\d+/);
      const textPart = topicWithTime.match(/[^\d]+/);

      if (timePart && textPart) {
        topics.push({topic: textPart[0], time: Number(timePart[0])});
      }

    })

    return topics;
  }

  onChange(event: any) {
    const file: File = event.target.files[0];
    if (file) {
      this.file = file;
      this.readFile(this.file);
    }
  }

  readFile(file: File) {
    const reader = new FileReader();
    reader.onload = () => {
      const fileContent = reader.result;
      this.fileContent = fileContent as string;
      console.log(this.fileContent);
    };
    reader.readAsText(file);
  }


}


<div>
  <form>
    <input type="file" [multiple]="false" (change)="onChange($event)">
  </form>
  <button (click)="organizarEvento()">Organizar</button>
</div>

<ng-container *ngIf="topics.length>0">
  <ng-container *ngFor="let topic of topics">
    <header><b>{{topic.name}}</b></header>
    <div *ngFor="let activitie of topic.activities">
      {{activitie|json}}
    </div>
  </ng-container>
</ng-container>

<router-outlet></router-outlet>

// conference-organizer/src/App.tsx
import React, { useState } from 'react'
import './App.css'
import { Conference } from "./models/conference.class";
import { EventOrganizer } from "./models/event-organizer.class";
import { Topic } from "./models/topic.class";


function App() {

  const [fileContent, setFileContent] = useState<string>('');
  const [res, setRes] = useState<{ topic: string, activities: string[] }[]>([]);


  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files) {
      readFile(e.target.files[0]);
    }
  };

  function readFile(file: File) {
    const reader = new FileReader();


    reader.onload = () => {
      const fileContentRes = reader.result as string;
      if (fileContentRes) setFileContent(fileContentRes as string)
    };

    reader.readAsText(file);

  }

  async function setData() {

    const topics: {
      topic: string
      time: number
    }[] = [];

    let textInput = fileContent.replaceAll('\n', '');

    const topicsWithTime = textInput.split('min')

    topicsWithTime.forEach((topicWithTime) => {

      const timePart = topicWithTime.match(/\d+/);
      const textPart = topicWithTime.match(/[^\d]+/);

      if (timePart && textPart) {
        topics.push({topic: textPart[0], time: Number(timePart[0])});
      }

    })

    return topics;
  }


  const organizarEvento = async () => {


    const topicsFromFile = await setData()

    if (!fileContent) return;
    const conferences: Conference[] = topicsFromFile.map(conference => new Conference(conference.time, conference.topic))

    let eventOrganizer!: EventOrganizer;

    eventOrganizer = new EventOrganizer({
          conferences,
          morningStartTime: 9,
          morningEndTime: 12,
          lunchTime: 12,
          minSocialEventTime: 16,
          maxSocialEventTime: 17,
          afternoonStartTime: 13,
        }
    )

    let topics: Topic[] = [];

    topics = eventOrganizer.organizeConferencesInTopics()

    let event: { topic: string, activities: string[] }[] = [];

    for (let topic of topics) {
      const eventToAdd: { topic: string, activities: string[] } = {topic: topic.name, activities: []};

      for (let activity of topic.activities) {
        if (activity instanceof Conference) {
          eventToAdd.activities.push(`${activity.startTime?.toLocaleTimeString('en-US', {
            hour: "numeric",
            minute: "numeric"
          })} ${activity.topic} ${activity.time}min`);
        } else {
          eventToAdd.activities.push(`${activity.startTime?.toLocaleTimeString('en-US', {
            hour: "numeric",
            minute: "numeric"
          })} ${activity.type}`);
        }

      }
      event.push(eventToAdd);
    }

    setRes(event);
  }

  return (
      <>
        <form>
          <input type="file" onChange={handleFileChange}/>
        </form>
        {fileContent && <button onClick={organizarEvento}>Organizar evento</button>}
        <div>{res.map((topic, index) => <>
          <header key={topic.topic}>{topic.topic}</header>
          {topic.activities.map((activitie, indexActivitie) => <div
              key={`${index}${indexActivitie}`}>{`${index}${indexActivitie}`} {activitie}</div>)}</>)}</div>

      </>
  )
}

export default App
